### ISSUE TITLE
Provider Crashes when State file is out of sync

### ISSUE THREAD

**Issue by JimHart2** [softlayer/terraform-provider-softlayer#154]
The Softlayer provider errors with "Unexpected EOF" messages and then crashes when the state file thinks that a resource should exist that does not exist in the SoftLayer Environment.

**Comment by minsikl** [comment]
Could you share sample tf and state files which crash the terraform?

**Comment by JimHart2** [comment]
Attached files are the relevant parts of the config, the whole crash log, and the who state file.  This is a test environment. 

[crash.log.txt](https://github.com/softlayer/terraform-provider-softlayer/files/1062069/crash.log.txt)
[terraform.tfstate.txt](https://github.com/softlayer/terraform-provider-softlayer/files/1062070/terraform.tfstate.txt)
[users.tf.txt](https://github.com/softlayer/terraform-provider-softlayer/files/1062071/users.tf.txt)

**Comment by renier** [comment]
@minsikl How are you reproducing this bug?

I tried `terraform refresh` and `terraform plan` using the provided files but it doesn't crash on the version of terraform indicated by the state file (i.e. 0.9.5). I also tried a cleaner state file with only the _btran_ user, but it didn't crash like that either.

**Comment by minsikl** [comment]
@renier You can reproduce this bug with the following step:
1) Create a user using terraform
2) Delete a user in SL Portal
3) execute `terraform refresh`

When a user is deleted, it has remained with "CANCEL_PENDING" status in a specific period. Although a user ID still exists, the user information is already removed. When `terraform refresh` is executed, isExist returns `true` as the ID still exists, but Read function is crashed because some fields are already deleted.
